#!/usr/bin/env bash
# This script display 20 times the number and in some iterations display words

c=1
while [ $c -lt 21 ];
do echo "$c"
case $c in
4)
echo "bad luck from China";;
9)
echo "bad luck from Japan";;
17)
echo "bad luck from Italy";;
esac
c=$(( c+1 )); done
