#!/usr/bin/env bash
# To file, or not to file.

fl=holbertonschool
if [ -e $fl ]; then
echo "holbertonschool file exists"
if [ -s $fl ]; then
echo "holbertonschool file is not empty"
else
echo "holbertonschool file is empty"
fi
if [ -f $fl ]; then
echo "holbertonschool is a regular file"
fi
else
echo "holbertonschool file does not exist"
fi
